version: '3.6'
services:
  nginx:
    image: nginx
    platform: linux/amd64
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/
      - ./docker/dev/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/dev/nginx/site.conf:/etc/nginx/sites-enabled/site.conf
    restart: unless-stopped

  php:
    build: docker/dev/php
    platform: linux/amd64
    volumes:
      - .:/var/www/html/
      - ./docker/php/config.d/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/config.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

    depends_on:
      - redis
    restart: unless-stopped
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:7.0.11-alpine
    restart: always

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    ports:
      - "8025:8025"
      - "1025:1025"
    restart: unless-stopped
    environment:
      - USERNAME=admin
      - PASSWORD=admin

  mysql:
    image: mysql:8.0
    platform: linux/amd64
    command: --general-log=1 --general-log-file=/tmp/my.log --innodb-buffer-pool-size=1G
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=customer_portal
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"

volumes:
  mysql-data:

